### ISSUE TITLE
Smooth level, an option to avoid sharp borders

### ISSUE THREAD

**Issue by arypbatista** [arypbatista/godot-bordered-polygon-2d#1]
Right now borders copy polygon's charcteristics. This leads to sharp corners. We want to smooth them by generating extra polygons around the corners.

**Comment by jtaart** [comment]
I'll try to make this tonight.

**Comment by jtaart** [comment]
WIP:
<a href="http://imgur.com/w4IyItC"><img src="http://i.imgur.com/w4IyItC.png" title="source: imgur.com" /></a>

**Comment by arypbatista** [comment]
This actually works really good but I think we have some issues with twisted borders. I have added a debug  example for testing this.

How do you think we should proceed @jtaart? Maybe we can fusion the points that originates the twist

**Comment by jtaart** [comment]
The twisting happens when a shape gets pushed to small, and the points of each side pass each other. This happens the most when overlapping is turned up. I have an idea how to fix it, but not sure if it will work.
