### ISSUE TITLE
I think we should delete convex_triad checks/rot in smooth_three_points().

### ISSUE THREAD

**Issue by jtaart** [arypbatista/godot-bordered-polygon-2d#14]
with it:
<a href="http://imgur.com/MvK3fGQ"><img src="http://i.imgur.com/MvK3fGQ.png" title="source: imgur.com" /></a>

with out it:
<a href="http://imgur.com/QK1QOTU"><img src="http://i.imgur.com/QK1QOTU.png" title="source: imgur.com" /></a>

**Comment by arypbatista** [comment]
Yeah, go ahead. Just thought it would be nice to solve convex and concave smoothing differently, or maybe it solved some twisted issues at that time.

**Comment by jtaart** [comment]
Never mind, it might not be this.
