### ISSUE TITLE
Material export option for the borders

### ISSUE THREAD

**Issue by jtaart** [arypbatista/godot-bordered-polygon-2d#16]
Its one of the reasons why I didn't use _draw(). It probably wont get used to much though.

**Comment by arypbatista** [comment]
So we can apply shaders to borders, for example?

**Comment by jtaart** [comment]
yeah

**Comment by arypbatista** [comment]
[TileSet](http://docs.godotengine.org/en/stable/classes/class_tileset.html?highlight=TileSet) supports individual materials for each border. So it is just about adding an option for the single border texture case. I will do this.

**Comment by arypbatista** [comment]
Done on 1234f50

**Comment by arypbatista** [comment]
Back to open until we have this pushed into `master`
