### ISSUE TITLE
Border material shader don't work on editor mode

### ISSUE THREAD

**Issue by arypbatista** [arypbatista/godot-bordered-polygon-2d#17]
When running scene you can perfectly see the material effect. But not in editor mode.

**Comment by arypbatista** [comment]
@jtaart Can you reproduce? Today I openned the editor and it was working fine!

**Comment by jtaart** [comment]
Yeah i can confirm, but multi border only works when you have a material in the single material slot. (I think i screwed this up). I guess we have to do a check per border, some how if that one is null.

**Comment by arypbatista** [comment]
Fixed by 8cd24ea
