### ISSUE TITLE
Sometimes border textures get stretched

### ISSUE THREAD

**Issue by arypbatista** [arypbatista/godot-bordered-polygon-2d#2]
Sometimes border textures get stretched. Let's fix that so texture repeats without stretching.

**Comment by jtaart** [comment]
If we make corner pieces/smoother this will most likely go away.

**Comment by arypbatista** [comment]
Yeah, but thinking on it in a more general way, I think there will be use cases where people want really sharp joints and this stretching issue will be something they want to get rid of (e.g. pixelart). In that scenario would be worthy to have it fixed.

**Comment by arypbatista** [comment]
Solved on #9
