### ISSUE TITLE
Border textures seems to be horizontally flipped

### ISSUE THREAD

**Issue by arypbatista** [arypbatista/godot-bordered-polygon-2d#26]
Border textures seems to be horizontally flipped

![image](https://cloud.githubusercontent.com/assets/4958871/23331985/4ef49ca6-fb4f-11e6-80d6-57d375397754.png)

**Comment by jtaart** [comment]
I think I just fixed this. (in pull)

**Comment by arypbatista** [comment]
Perfect, fixed by #27
