### ISSUE TITLE
Incorrect uv mapping?

### ISSUE THREAD

**Issue by tommila** [arypbatista/godot-bordered-polygon-2d#38]
Hey.

Noticed some wacky texture uv mapping that can be seen in one of the examples.
![screenshot - 260317 - 20 38 55](https://cloud.githubusercontent.com/assets/6402990/24333868/9610f3b6-1268-11e7-92f9-8c2fc704447a.png)

i wonder if this is made by design or if it's just a mistake.
Anyways, i made an ugly fix that resolves this issue:

```
func create_border(width, height, quad, offset=Vector2(0,0)):
	var border = Polygon2D.new()
	border.set_name('Border')
	var border_angle = quad_angle(quad)

	var n = (quad[1] - quad[0]).normalized()
	var phi = Vector2(-1,0).angle_to(n)
		
	var top_width = quad[0].distance_to(quad[1])
	var bottom_width = quad[2].distance_to(quad[3])

	var bottom_x = (quad[0] - quad[3]).rotated(-phi).x
	
	border.set_uv([Vector2(0, 0) + offset, 
		Vector2(0 + top_width, 0) + offset, 
		Vector2(bottom_x + bottom_width, height) + offset, 
		Vector2(bottom_x, height) + offset])
	border.set_polygon(quad)
```
![screenshot - 260317 - 20 48 58](https://cloud.githubusercontent.com/assets/6402990/24333903/3de61ec2-1269-11e7-881b-e93b38e54903.png)

Nice addon btw.

**Comment by arypbatista** [comment]
Nice catch @tommila ! Would you like to contribute? You can fork and pull-request with this same fix.

This addon is under development, there are a bunch of stuff we still to fix and implement, but overall is good.

**Comment by tommila** [comment]
Sure, why not.

**Comment by arypbatista** [comment]
Solved thanks to you @tommila

**Comment by tommila** [comment]
Hmm, there's still something fishy going on with the seams. I'll look into it.

**Comment by arypbatista** [comment]
Yeah, I should improve examples. But I think this is pretty good right now. Thanks for your collaboration!!
