### ISSUE TITLE
Invalid call. Nonexistent function 'tile_get_texture' in base 'ImageTexture'.

### ISSUE THREAD

**Issue by Stevo91** [arypbatista/godot-bordered-polygon-2d#40]
Hi, I tried using this add on but hit this error message for nonexistent function. I'm using the 0.2 version from the asset library for GODOT v2.1.2.
![error1](https://cloud.githubusercontent.com/assets/28237414/25568749/ad1b6e2e-2e01-11e7-8d33-9ad5881172b9.png)
![error2](https://cloud.githubusercontent.com/assets/28237414/25568751/b21cf000-2e01-11e7-9f4d-5ff5a790545c.png)

**Comment by jtaart** [comment]
It looks like you put a texture where a tile map should be. Try making **Border Textures**  null. (**Border Textures** is optional so you can delete it)

**Comment by Stevo91** [comment]
Ah okay, yes I now see the difference between textures and texture here. I should be able to make good use of this plug in. Thx.
![texture border](https://cloud.githubusercontent.com/assets/28237414/25598024/4d64c1be-2eca-11e7-9a9f-bdde8a74dbba.png)
