### ISSUE TITLE
Polygons don't draw if you don't put a Border texture

### ISSUE THREAD

**Issue by Keyaku** [arypbatista/godot-bordered-polygon-2d#41]
Normal Polygon2D nodes draw the color you give to them, regardless of whether or not you give them a texture.

**Expected**:
The functionality from Polygon2D should maintain.

**Actual result**:
With BorderedPolygon2D, they don't draw at all if `border_texture` is `null`.

**Comment by arypbatista** [comment]
Solved by #43
