### ISSUE TITLE
Automatic lighting?

### ISSUE THREAD

**Issue by arypbatista** [arypbatista/godot-bordered-polygon-2d#5]
Probably this will become an independent node, but it is really similar:

I am working in a isometric game project where map is drawn using this BorderedPolygon2D. The game is about a character travelling hell. There is a ground, were the character can walk, sorrounded by shinny lava. The thing is I need to add lights to the map: on the bottom borders I need a light to get over the border so it takes the glow from lava, and behind the top border another light for it to make a more palid orange light product of the lava that is in the border but is hidden due to perspective.

![Game Project Image](https://scontent-eze1-1.xx.fbcdn.net/v/t1.0-9/16729374_1185693614813085_262269901861920640_n.jpg?oh=d368d2f838bbcaf6253756ce67929aca&oe=5900FBAD)

@jtaart Do you have any advice on how should I implement this? Maybe, instead of a polygon, I could have a multi-segment line that goes from coast to coast generating light2D nodes. And to place another multi-segment line, behind ground, for the effect on the top borders.

**Comment by jtaart** [comment]
I would try editing https://github.com/RodZill4/godot-platform2d to lay a light down ever so many backed curved points.

**Comment by jtaart** [comment]
You know you could convert the outside points of bordered-polygon-2d then turn it into a curve. Then place the lights on top of its backed intervals.

**Comment by arypbatista** [comment]
Just wondering the performance implications of doing this. I will share the results once I try what you suggest

**Comment by jtaart** [comment]
I have heard people say 2D lighting well get faster in Godot 3

**Comment by arypbatista** [comment]
Nice
